import type { Static } from '@sinclair/typebox';
export declare const InvoiceStatusSchema: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>;
export type InvoiceStatus = Static<typeof InvoiceStatusSchema>;
export declare const InvoiceLineItemSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    invoiceId: import("@sinclair/typebox").TString;
    lineNumber: import("@sinclair/typebox").TNumber;
    description: import("@sinclair/typebox").TString;
    quantity: import("@sinclair/typebox").TNumber;
    unitPrice: import("@sinclair/typebox").TNumber;
    subtotal: import("@sinclair/typebox").TNumber;
    taxRate: import("@sinclair/typebox").TNumber;
    taxAmount: import("@sinclair/typebox").TNumber;
    totalAmount: import("@sinclair/typebox").TNumber;
    metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
    createdAt: import("@sinclair/typebox").TString;
    updatedAt: import("@sinclair/typebox").TString;
}>;
export type InvoiceLineItem = Static<typeof InvoiceLineItemSchema>;
export declare const PaymentSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    invoiceId: import("@sinclair/typebox").TString;
    amount: import("@sinclair/typebox").TNumber;
    currency: import("@sinclair/typebox").TString;
    paymentDate: import("@sinclair/typebox").TString;
    paymentMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    reference: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    createdAt: import("@sinclair/typebox").TString;
    updatedAt: import("@sinclair/typebox").TString;
}>;
export type Payment = Static<typeof PaymentSchema>;
export declare const InvoiceCustomerSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    name: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    phone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type InvoiceCustomer = Static<typeof InvoiceCustomerSchema>;
export declare const InvoiceSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    organizationId: import("@sinclair/typebox").TString;
    invoiceNumber: import("@sinclair/typebox").TString;
    customerId: import("@sinclair/typebox").TString;
    projectId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    quoteId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    currency: import("@sinclair/typebox").TString;
    subtotal: import("@sinclair/typebox").TNumber;
    taxAmount: import("@sinclair/typebox").TNumber;
    discountAmount: import("@sinclair/typebox").TNumber;
    totalAmount: import("@sinclair/typebox").TNumber;
    paidAmount: import("@sinclair/typebox").TNumber;
    balanceAmount: import("@sinclair/typebox").TNumber;
    status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>;
    issuedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    paidAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    overdueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    writtenOffAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    title: import("@sinclair/typebox").TString;
    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    termsConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    internalNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
    customer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        name: import("@sinclair/typebox").TString;
        email: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        phone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    lineItems: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        invoiceId: import("@sinclair/typebox").TString;
        lineNumber: import("@sinclair/typebox").TNumber;
        description: import("@sinclair/typebox").TString;
        quantity: import("@sinclair/typebox").TNumber;
        unitPrice: import("@sinclair/typebox").TNumber;
        subtotal: import("@sinclair/typebox").TNumber;
        taxRate: import("@sinclair/typebox").TNumber;
        taxAmount: import("@sinclair/typebox").TNumber;
        totalAmount: import("@sinclair/typebox").TNumber;
        metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
        createdAt: import("@sinclair/typebox").TString;
        updatedAt: import("@sinclair/typebox").TString;
    }>>>;
    payments: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        invoiceId: import("@sinclair/typebox").TString;
        amount: import("@sinclair/typebox").TNumber;
        currency: import("@sinclair/typebox").TString;
        paymentDate: import("@sinclair/typebox").TString;
        paymentMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        reference: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        createdAt: import("@sinclair/typebox").TString;
        updatedAt: import("@sinclair/typebox").TString;
    }>>>;
    createdBy: import("@sinclair/typebox").TString;
    approvedBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    approvedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    createdAt: import("@sinclair/typebox").TString;
    updatedAt: import("@sinclair/typebox").TString;
    etag: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type Invoice = Static<typeof InvoiceSchema>;
export declare const CreateInvoiceSchema: import("@sinclair/typebox").TObject<{
    customerId: import("@sinclair/typebox").TString;
    projectId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    quoteId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    title: import("@sinclair/typebox").TString;
    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    termsConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    currency: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    lineItems: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        description: import("@sinclair/typebox").TString;
        quantity: import("@sinclair/typebox").TNumber;
        unitPrice: import("@sinclair/typebox").TNumber;
    }>>>;
    metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
}>;
export type CreateInvoice = Static<typeof CreateInvoiceSchema>;
export declare const UpdateInvoiceSchema: import("@sinclair/typebox").TObject<{
    title: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    termsConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
}>;
export type UpdateInvoice = Static<typeof UpdateInvoiceSchema>;
export declare const InvoiceStatusTransitionSchema: import("@sinclair/typebox").TObject<{
    status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>;
    reason: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    effectiveDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type InvoiceStatusTransition = Static<typeof InvoiceStatusTransitionSchema>;
export declare const MarkInvoicePaidSchema: import("@sinclair/typebox").TObject<{
    paymentDate: import("@sinclair/typebox").TString;
    amount: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    paymentMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    reference: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type MarkInvoicePaid = Static<typeof MarkInvoicePaidSchema>;
export declare const VoidInvoiceSchema: import("@sinclair/typebox").TObject<{
    reason: import("@sinclair/typebox").TString;
    effectiveDate: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type VoidInvoice = Static<typeof VoidInvoiceSchema>;
export declare const InvoiceListFiltersSchema: import("@sinclair/typebox").TObject<{
    status: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>>;
    customerId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    projectId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    currency: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    issuedAfter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    issuedBefore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueAfter: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueBefore: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    minAmount: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    maxAmount: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    search: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    page: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    limit: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TNumber>;
    sort: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    sortOrder: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"asc">, import("@sinclair/typebox").TLiteral<"desc">]>>;
}>;
export type InvoiceListFilters = Static<typeof InvoiceListFiltersSchema>;
export declare const InvoiceResponseSchema: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    organizationId: import("@sinclair/typebox").TString;
    invoiceNumber: import("@sinclair/typebox").TString;
    customerId: import("@sinclair/typebox").TString;
    projectId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    quoteId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    currency: import("@sinclair/typebox").TString;
    subtotal: import("@sinclair/typebox").TNumber;
    taxAmount: import("@sinclair/typebox").TNumber;
    discountAmount: import("@sinclair/typebox").TNumber;
    totalAmount: import("@sinclair/typebox").TNumber;
    paidAmount: import("@sinclair/typebox").TNumber;
    balanceAmount: import("@sinclair/typebox").TNumber;
    status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>;
    issuedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    dueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    paidAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    overdueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    writtenOffAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    title: import("@sinclair/typebox").TString;
    description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    termsConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    internalNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
    customer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        name: import("@sinclair/typebox").TString;
        email: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        phone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    lineItems: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        invoiceId: import("@sinclair/typebox").TString;
        lineNumber: import("@sinclair/typebox").TNumber;
        description: import("@sinclair/typebox").TString;
        quantity: import("@sinclair/typebox").TNumber;
        unitPrice: import("@sinclair/typebox").TNumber;
        subtotal: import("@sinclair/typebox").TNumber;
        taxRate: import("@sinclair/typebox").TNumber;
        taxAmount: import("@sinclair/typebox").TNumber;
        totalAmount: import("@sinclair/typebox").TNumber;
        metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
        createdAt: import("@sinclair/typebox").TString;
        updatedAt: import("@sinclair/typebox").TString;
    }>>>;
    payments: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        invoiceId: import("@sinclair/typebox").TString;
        amount: import("@sinclair/typebox").TNumber;
        currency: import("@sinclair/typebox").TString;
        paymentDate: import("@sinclair/typebox").TString;
        paymentMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        reference: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        createdAt: import("@sinclair/typebox").TString;
        updatedAt: import("@sinclair/typebox").TString;
    }>>>;
    createdBy: import("@sinclair/typebox").TString;
    approvedBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    approvedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    createdAt: import("@sinclair/typebox").TString;
    updatedAt: import("@sinclair/typebox").TString;
    etag: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export declare const InvoiceListResponseSchema: import("@sinclair/typebox").TObject<{
    data: import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
        id: import("@sinclair/typebox").TString;
        organizationId: import("@sinclair/typebox").TString;
        invoiceNumber: import("@sinclair/typebox").TString;
        customerId: import("@sinclair/typebox").TString;
        projectId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        quoteId: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        currency: import("@sinclair/typebox").TString;
        subtotal: import("@sinclair/typebox").TNumber;
        taxAmount: import("@sinclair/typebox").TNumber;
        discountAmount: import("@sinclair/typebox").TNumber;
        totalAmount: import("@sinclair/typebox").TNumber;
        paidAmount: import("@sinclair/typebox").TNumber;
        balanceAmount: import("@sinclair/typebox").TNumber;
        status: import("@sinclair/typebox").TUnion<[import("@sinclair/typebox").TLiteral<"draft">, import("@sinclair/typebox").TLiteral<"sent">, import("@sinclair/typebox").TLiteral<"part_paid">, import("@sinclair/typebox").TLiteral<"paid">, import("@sinclair/typebox").TLiteral<"overdue">, import("@sinclair/typebox").TLiteral<"written_off">, import("@sinclair/typebox").TLiteral<"void">]>;
        issuedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        dueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        paidAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        overdueAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        writtenOffAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        title: import("@sinclair/typebox").TString;
        description: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        termsConditions: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        internalNotes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
        customer: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TString;
            name: import("@sinclair/typebox").TString;
            email: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            phone: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            address: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        }>>;
        lineItems: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TString;
            invoiceId: import("@sinclair/typebox").TString;
            lineNumber: import("@sinclair/typebox").TNumber;
            description: import("@sinclair/typebox").TString;
            quantity: import("@sinclair/typebox").TNumber;
            unitPrice: import("@sinclair/typebox").TNumber;
            subtotal: import("@sinclair/typebox").TNumber;
            taxRate: import("@sinclair/typebox").TNumber;
            taxAmount: import("@sinclair/typebox").TNumber;
            totalAmount: import("@sinclair/typebox").TNumber;
            metadata: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
            createdAt: import("@sinclair/typebox").TString;
            updatedAt: import("@sinclair/typebox").TString;
        }>>>;
        payments: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TObject<{
            id: import("@sinclair/typebox").TString;
            invoiceId: import("@sinclair/typebox").TString;
            amount: import("@sinclair/typebox").TNumber;
            currency: import("@sinclair/typebox").TString;
            paymentDate: import("@sinclair/typebox").TString;
            paymentMethod: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            reference: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            notes: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
            createdAt: import("@sinclair/typebox").TString;
            updatedAt: import("@sinclair/typebox").TString;
        }>>>;
        createdBy: import("@sinclair/typebox").TString;
        approvedBy: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        approvedAt: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
        createdAt: import("@sinclair/typebox").TString;
        updatedAt: import("@sinclair/typebox").TString;
        etag: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    }>>;
    pagination: import("@sinclair/typebox").TObject<{
        page: import("@sinclair/typebox").TNumber;
        limit: import("@sinclair/typebox").TNumber;
        total: import("@sinclair/typebox").TNumber;
        totalPages: import("@sinclair/typebox").TNumber;
        hasNext: import("@sinclair/typebox").TBoolean;
        hasPrev: import("@sinclair/typebox").TBoolean;
    }>;
    etag: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
}>;
export type InvoiceListResponse = Static<typeof InvoiceListResponseSchema>;
export declare const InvoiceErrorSchema: import("@sinclair/typebox").TObject<{
    error: import("@sinclair/typebox").TString;
    message: import("@sinclair/typebox").TString;
    code: import("@sinclair/typebox").TString;
    details: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TRecord<import("@sinclair/typebox").TString, import("@sinclair/typebox").TAny>>;
}>;
export type InvoiceError = Static<typeof InvoiceErrorSchema>;
//# sourceMappingURL=typeboxSchemas.d.ts.map