import type { AuditLogger } from '../../lib/audit-logger.drizzle.js';
export interface QuoteContext {
    organizationId: string;
    userId: string;
}
export declare class QuoteService {
    private context;
    private auditLogger?;
    private db;
    constructor(context: QuoteContext, auditLogger?: AuditLogger | undefined);
    listQuotes(pagination?: {
        page?: number;
        size?: number;
    }, filters?: any): Promise<{
        quotes: {
            id: string;
            organizationId: string;
            quoteNumber: string;
            customerId: string;
            projectId: string | null;
            title: string;
            description: string | null;
            status: string;
            type: string;
            validFrom: string;
            validUntil: string;
            currency: string;
            exchangeRate: string;
            subtotal: string;
            taxRate: string;
            taxAmount: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            totalAmount: string;
            termsConditions: string | null;
            notes: string | null;
            internalNotes: string | null;
            createdBy: string;
            approvedBy: string | null;
            approvedAt: Date | null;
            sentAt: Date | null;
            acceptedAt: Date | null;
            expiresAt: Date | null;
            metadata: unknown;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
        }[];
        pagination: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    getQuoteById(id: string): Promise<{
        id: string;
        organizationId: string;
        quoteNumber: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null>;
    createQuote(data: any): Promise<{
        id: string;
        organizationId: string;
        quoteNumber: string;
        customerId: any;
        projectId: any;
        title: any;
        description: any;
        status: string;
        type: any;
        validFrom: Date;
        validUntil: Date;
        currency: any;
        exchangeRate: any;
        subtotal: any;
        taxRate: any;
        taxAmount: any;
        discountType: any;
        discountValue: any;
        discountAmount: any;
        totalAmount: any;
        termsConditions: any;
        notes: any;
        internalNotes: any;
        createdBy: string;
        approvedBy: null;
        approvedAt: null;
        sentAt: null;
        acceptedAt: null;
        rejectedAt: null;
        metadata: any;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateQuote(id: string, data: any): Promise<{
        id: string;
        organizationId: string;
        quoteNumber: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null>;
    transitionStatus(id: string, data: {
        status: string;
        reason?: string;
    }): Promise<{
        id: string;
        organizationId: string;
        quoteNumber: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
    } | null>;
    getQuoteVersions(quoteId: string): Promise<{
        id: string;
        quoteId: string;
        versionNumber: number;
        organizationId: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
    }[]>;
    getQuoteVersion(quoteId: string, versionId: string): Promise<{
        id: string;
        quoteId: string;
        versionNumber: number;
        organizationId: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
    } | null>;
    private generateQuoteNumber;
}
//# sourceMappingURL=service.d.ts.map