import type { AuditLogger } from '../../lib/audit-logger.drizzle.js';
export interface QuoteContext {
    organizationId: string;
    userId: string;
}
export declare class QuoteService {
    private context;
    private auditLogger?;
    private db;
    constructor(context: QuoteContext, auditLogger?: AuditLogger | undefined);
    listQuotes(pagination?: {
        page?: number;
        size?: number;
    }, filters?: any): Promise<{
        data: {
            id: string;
            organizationId: string;
            tenantId: string | null;
            quoteNumber: string;
            customerId: string;
            projectId: string | null;
            title: string;
            description: string | null;
            status: string;
            type: string;
            validFrom: string;
            validUntil: string;
            currency: string;
            exchangeRate: string;
            subtotal: string;
            taxRate: string;
            taxAmount: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            totalAmount: string;
            termsConditions: string | null;
            notes: string | null;
            internalNotes: string | null;
            createdBy: string;
            approvedBy: string | null;
            approvedAt: Date | null;
            sentAt: Date | null;
            acceptedAt: Date | null;
            expiresAt: Date | null;
            deliveredAt: Date | null;
            viewedAt: Date | null;
            publicToken: string | null;
            tokenExpiresAt: Date | null;
            tokenUsedAt: Date | null;
            metadata: unknown;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
        }[];
        pagination: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
            hasNext: boolean;
            hasPrev: boolean;
        };
    }>;
    getQuoteById(id: string): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    updateQuote(id: string, data: any): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    transitionStatus(id: string, data: {
        status: string;
        reason?: string;
    }): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    getQuoteVersions(quoteId: string): Promise<{
        id: string;
        quoteId: string;
        versionNumber: number;
        organizationId: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
    }[]>;
    getQuoteVersion(quoteId: string, versionId: string): Promise<{
        id: string;
        quoteId: string;
        versionNumber: number;
        organizationId: string;
        customerId: string;
        projectId: string | null;
        title: string;
        description: string | null;
        status: string;
        type: string;
        validFrom: string;
        validUntil: string;
        currency: string;
        exchangeRate: string;
        subtotal: string;
        taxRate: string;
        taxAmount: string;
        discountType: string;
        discountValue: string;
        discountAmount: string;
        totalAmount: string;
        termsConditions: string | null;
        notes: string | null;
        internalNotes: string | null;
        createdBy: string;
        approvedBy: string | null;
        approvedAt: Date | null;
        sentAt: Date | null;
        acceptedAt: Date | null;
        expiresAt: Date | null;
        metadata: unknown;
        createdAt: Date;
    } | null>;
    private generateQuoteNumber;
    createQuote(data: {
        clientId: string;
        title: string;
        description?: string;
        type: string;
        status: string;
        validUntil?: string;
        metadata: Record<string, any>;
    }): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: Record<string, any>;
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: never[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    }>;
    addLineItem(quoteId: string, data: {
        description: string;
        quantity: number;
        unitPrice: number;
        metadata?: Record<string, any>;
    }): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    updateLineItem(quoteId: string, lineItemId: string, data: {
        description?: string;
        quantity?: number;
        unitPrice?: number;
        metadata?: Record<string, any>;
    }): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    deleteLineItem(quoteId: string, lineItemId: string): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    private recalculateQuoteTotals;
    setDiscount(quoteId: string, discount: {
        type: 'percentage' | 'fixed';
        value: number;
    }): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
    updateQuoteStatus(quoteId: string, status: string): Promise<{
        id: string;
        clientId: string;
        title: string;
        description: string | null;
        type: string;
        status: string;
        validUntil: string | null;
        metadata: {
            currency: string;
            discountType: string;
            discountValue: string;
            discountAmount: string;
            taxRate: string;
        };
        organizationId: string;
        createdAt: string;
        updatedAt: string;
        lineItems: {
            id: string;
            description: string;
            quantity: number;
            unitPrice: number;
            totalPrice: number;
            metadata: {};
        }[];
        subtotal: number;
        taxAmount: number;
        totalAmount: number;
        createdBy: string;
        quoteNumber: string;
    } | null>;
}
//# sourceMappingURL=service.d.ts.map