import '../config/load-test-env.js';
import { getRedisClient } from '@pivotal-flow/shared/redis';
import type { FastifyInstance } from 'fastify';
import { getDatabase } from '../lib/db.js';
import { organizations, users, customers, roles } from '../lib/schema.js';
declare let testDb: ReturnType<typeof getDatabase>;
declare let testRedis: ReturnType<typeof getRedisClient>;
declare let app: FastifyInstance;
declare const testUtils: {
    generateId(): string;
    createTestOrganization(data?: Partial<typeof organizations.$inferInsert>): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        industry: string | null;
        website: string | null;
        size: string | null;
        deletedAt: Date | null;
        street: string | null;
        suburb: string | null;
        city: string | null;
        region: string | null;
        postcode: string | null;
        country: string | null;
        phone: string | null;
        email: string | null;
        contactExtras: unknown;
        slug: string;
        domain: string | null;
        timezone: string;
        currency: string;
        taxId: string | null;
        settings: unknown;
        subscriptionPlan: string;
        subscriptionStatus: string;
        trialEndsAt: Date | null;
    }>;
    createTestUser(data?: Partial<typeof users.$inferInsert>): Promise<{
        id: string;
        metadata: unknown;
        createdAt: Date;
        updatedAt: Date;
        organizationId: string;
        status: string;
        deletedAt: Date | null;
        phone: string | null;
        email: string;
        timezone: string;
        username: string | null;
        firstName: string;
        lastName: string;
        displayName: string | null;
        avatarUrl: string | null;
        locale: string;
        emailVerified: boolean;
        emailVerifiedAt: Date | null;
        lastLoginAt: Date | null;
        loginCount: number;
        failedLoginAttempts: number;
        lockedUntil: Date | null;
        passwordHash: string | null;
        mfaEnabled: boolean;
        mfaSecret: string | null;
        preferences: unknown;
        dateFormat: string;
        timeFormat: string;
        customerId: string | null;
        userType: string;
        passwordHashAlgo: string | null;
        passwordHashSalt: string | null;
    }>;
    createTestCustomer(organizationId: string, data?: Partial<typeof customers.$inferInsert>): Promise<{
        id: string;
        description: string | null;
        createdAt: Date;
        updatedAt: Date;
        organizationId: string;
        customerNumber: string;
        companyName: string;
        legalName: string | null;
        industry: string | null;
        website: string | null;
        status: string;
        customerType: string;
        source: string | null;
        tags: string[] | null;
        rating: number | null;
        deletedAt: Date | null;
        street: string | null;
        suburb: string | null;
        city: string | null;
        region: string | null;
        postcode: string | null;
        country: string | null;
        phone: string | null;
        email: string | null;
        contactExtras: unknown;
        tenantId: string | null;
    }>;
    createTestRole(organizationId: string, data?: Partial<typeof roles.$inferInsert>): Promise<{
        id: string;
        name: string;
        description: string | null;
        createdAt: Date;
        updatedAt: Date;
        organizationId: string;
        isActive: boolean;
        isSystem: boolean;
    }>;
    generateTestToken(userId: string, organizationId: string, permissions?: string[]): string;
    cleanupTestData(): Promise<void>;
};
export { app, testDb, testRedis, testUtils };
//# sourceMappingURL=setup.d.ts.map