# infra/docker/docker-compose.app.yml

services:
  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ../../.env.example
      - ../../apps/backend/.env.example
      - ../../.env
    environment:
      PORT: 3000
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://pivotal:pivotal@postgres:5432/pivotal
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - devnet
    # Healthcheck is now built into the Dockerfile

  frontend:
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - devnet

  migrate:
    image: node:20-alpine
    working_dir: /app
    env_file:
      - ../../.env.example
      - ../../apps/backend/.env.example
      - ../../.env
    volumes:
      - ../..:/app
    entrypoint: [ "sh", "-lc", "cd apps/backend && corepack enable && pnpm install && npx prisma migrate deploy" ]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devnet
    restart: "no"

networks:
  devnet:
    external: true
